version: 2
updates:
  # Enable version updates for npm (main workspace)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "SpeechWriter-team"
    assignees:
      - "SpeechWriter-team"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"
          - "typescript"
          - "husky"
          - "lint-staged"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "react*"
          - "next*"
          - "@radix-ui/*"
          - "tailwindcss"
          - "framer-motion"
      security-updates:
        applies-to: security-updates

  # Enable version updates for npm (web app)
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "SpeechWriter-team"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (api)
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "SpeechWriter-team"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (ui package)
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "SpeechWriter-team"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for npm (config package)  
  - package-ecosystem: "npm"
    directory: "/packages/config"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "SpeechWriter-team"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "SpeechWriter-team"
    commit-message:
      prefix: "ci"
      include: "scope"