[build]
  base = "."
  command = "pnpm build"
  publish = "apps/web/out"
  
  # Environment variables - Use stable versions
  [build.environment]
    NODE_VERSION = "18.19.0"
    PNPM_VERSION = "8.15.0"
    PYTHON_VERSION = "3.11"
    NPM_FLAGS = "--legacy-peer-deps"

# API Functions (Netlify Functions)
[functions]
  directory = "apps/api/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "openai", "@aws-sdk/client-s3"]

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Next.js assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API redirects to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment-specific settings
[context.production]
  command = "pnpm build"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "pnpm build"
  [context.deploy-preview.environment]
    NODE_ENV = "preview"

[context.branch-deploy]
  command = "pnpm build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"